### ISSUE TITLE
Twitter posts no longer are working after June 11th, 2013

### ISSUE THREAD

**Issue by jsieber-old** [cfjedimaster/ColdFusion-Blog-Aggregator#2]
The twitter posts are no longer working as of June 11th, 2013. I tried updating to the twitter4j-core-3.0.4-SNAPSHOT.jar, but i;m having issues calling the setOAuthConsumer method.

**Comment by cfjedimaster** [comment]
The 1.0 API is officially dead. So - this whole feature probably needs updating or removing.

**Comment by amyers735** [comment]
Issue #3 has fixed this, as far as I can tell.  Should this issue be closed?

**Comment by cfjedimaster** [comment]
Um, sure. :)
